spring.application.name=MySpringBoot

# port number
server.port=8080

# \uC0AC\uC6A9\uC790 \uC815\uC758 \uD658\uACBD \uBCC0\uC218
myboot.name=MySpring
myboot.age=${random.int(1,100}
myboot.fullName=${myboot.name} Boot